---
  
 - name: Launch instance
   ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"  
      user_data: "{{ lookup('file', 'files/user_data.sh') }}"
      wait: true
      wait_timeout: 600
      region: "{{ region }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
      instance_tags: Name=ansible
   register: ec2

   # - name: Add new instance to host group
   #   add_host:
   #      hostname: "{{ item.public_ip }}"
   #      groupname: launched
   #      inventory_dir: /etc/ansible/
   #   with_items: "{{ ec2.instances }}"
  
 - name: print ip
   debug:
           msg: "{{ item.public_dns_name }}"

   with_items: "{{ ec2.instances }}"
   
 
 - name: add ip
   lineinfile:
              path: /home/ansible/please/inv
              regexp: '^[new_servers]  '
              line: 
                    "{{ item.public_dns_name }}"
              insertafter: '^[new_servers]'
              # create: yes
   with_items: "{{ ec2.instances }}"  
   become: yes   
   


   # - name: Add new instance to host group
   #   add_host:
   #        inventory_dir: /etc/ansible/hosts
   #        hostname: "{{ item.public_dns_name }}"
   #        groupname: launched
   #
   #   with_items: "{{ ec2.instances }}"
   #   become: yes
   #           
     
 - name: Wait for SSH to come up
   wait_for:
           host: "{{ item.public_dns_name }}"
           port: 22
           delay: 60
           timeout: 320
           state: started
   with_items: "{{ ec2.instances }}"
   
   # - name: copy ssh key
   #   shell: ssh-copy-id ansible@ "{{ item.public_dns_name }}"
   #   with_items: "{{ ec2.instances }}"   
   #
   # - name: copy ssh key
   #   authorized_key:
   #           
   #           user: ansible
   #           state: present
   #           key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
   #           path: "{{ public_dns_name }}"/home/ansible/.ssh/   
      
   # - name: copy ssh
   #   shell: scp /home/ansible/.ssh/id_rsa  ansible@"{{ item.public_dns_name }}":/root/.ssh/id_rsa
   #   with_items: "{{ ec2.instances }}"
   #   become: yes
   #

